import {GameBoard} from "/components/game-board/game-board.js";
import {GameChoice} from "/components/game-choice/game-choice.js";
import {HomePage} from "/components/home-page/home-page.js";
import {ProfilPage} from "/components/profil-page/app-profil-page/profil-page.js";
import {Pages} from "/components/pages/pages.js";
import {Button} from "/components/button/button.js";
import {ProfilPageButton} from "/components/profil-page/profil-page-button/profil-page-button.js";
import {HelpPage} from "/components/help-page/help-page.js";
import {Control} from "/components/control/control.js";
import {GameMaster} from "/components/game-master/game-master.js";
import {Popup} from "/components/popup/popup.js";
import {SignUpPopup} from "/components/sign-up-popup/sign-up-popup.js";
import {SignInPopup} from "/components/sign-in-popup/sign-in-popup.js";
import {Input} from "/components/input/input.js";
import {ForgetPassword} from "/components/forget-password-popup/forget-password-popup.js";

customElements.define("app-game-board", GameBoard);
customElements.define("app-game-choice", GameChoice);
customElements.define("app-home-page", HomePage);
customElements.define("app-profil-page", ProfilPage);
customElements.define("app-pages", Pages);
customElements.define("app-button", Button);
customElements.define("app-profil-page-button", ProfilPageButton);
customElements.define("app-help-page", HelpPage);
customElements.define("app-control", Control);
customElements.define("app-game-master", GameMaster);
customElements.define("app-popup", Popup);
customElements.define("app-sign-up-popup", SignUpPopup);
customElements.define("app-sign-in-popup", SignInPopup);
customElements.define("app-input", Input);
customElements.define("app-forget-password-popup", ForgetPassword);
