import {GameBoard} from "/components/game-board/game-board.js";
import {GameChoice} from "/components/game-choice/game-choice.js";
import {HomePage} from "/components/home-page/home-page.js";
import {ProfilPage} from "/components/profil-page/app-profil-page/profil-page.js";
import {Pages} from "/components/pages/pages.js";
import {Button} from "/components/button/button.js";
import {ProfilPageButton} from "/components/profil-page/profil-page-button/profil-page-button.js";
import {HelpPage} from "/components/help-page/help-page.js";
import {Control} from "/components/control/control.js";
import {GameMaster} from "/components/game-master/game-master.js";
import {Popup} from "/components/popup/popup.js";
import {SignUpPopup} from "/components/sign-up-popup/sign-up-popup.js";
import {SignInPopup} from "/components/sign-in-popup/sign-in-popup.js";
import {Input} from "/components/input/input.js";
import {ForgetPassword} from "/components/forget-password-popup/forget-password-popup.js";
import {ProfilDisplay} from "/components/profil-display/profil-display.js";
import {LoginContainer} from "/components/login-container/login-container.js";
import {ChatDrawer} from "/components/chat-drawer/chat-drawer.js";
import {TabNavigation} from "/components/tab-navigation/tab-navigation.js";
import {ChatTab} from "/components/chat-tab/chat-tab.js";
import {ChatSelection} from "/components/chat-selection/chat-selection.js";
import {ChatRoomButton} from "/components/chat-room-button/chat-room-button.js";
import {ChatRoom} from "/components/chat-room/chat-room.js";
import {ChatRoomMessage} from "/components/chat-room-message/chat-room-message.js";

customElements.define("app-game-board", GameBoard);
customElements.define("app-game-choice", GameChoice);
customElements.define("app-home-page", HomePage);
customElements.define("app-profil-page", ProfilPage);
customElements.define("app-pages", Pages);
customElements.define("app-button", Button);
customElements.define("app-profil-page-button", ProfilPageButton);
customElements.define("app-help-page", HelpPage);
customElements.define("app-control", Control);
customElements.define("app-game-master", GameMaster);
customElements.define("app-popup", Popup);
customElements.define("app-sign-up-popup", SignUpPopup);
customElements.define("app-sign-in-popup", SignInPopup);
customElements.define("app-input", Input);
customElements.define("app-reset-password-popup", ForgetPassword);
customElements.define("app-profile-display", ProfilDisplay);
customElements.define("app-login-container", LoginContainer);
customElements.define("app-tab-navigation", TabNavigation);
customElements.define("app-chat-drawer", ChatDrawer);
customElements.define("app-chat-tab", ChatTab);
customElements.define("app-chat-selection", ChatSelection);
customElements.define("app-chat-room-button", ChatRoomButton);
customElements.define("app-chat-room", ChatRoom);
customElements.define("app-chat-room-message", ChatRoomMessage);

